version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_DATABASE: mydb
      DB_USERNAME: root
      DB_PASSWORD: 123456
    volumes:
      - .:/var/www
    working_dir: /var/www

  nginx:
    depends_on:
      - php
    image: nginx:1.12
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: mydb
    ports:
      - 3306:3306
    volumes:
      - ./.db_data:/var/lib/mysql
