version: '3'

services:
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:/var/www
    working_dir: /var/www

  nginx:
    depends_on:
      - php
    image: nginx:1.12
    ports:
      - 80:80
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /var/www

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - 3306:3306
    volumes:
      - ./.db_data:/var/lib/mysql

  redis:
    image: redis:4.0
    ports:
      - 6379:6379
    volumes:
      - ./.rds_data:/data

  cron:
    build:
      context: .
      dockerfile: ./docker/cron/Dockerfile
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:/var/www
    working_dir: /var/www

  queue:
    build:
      context: .
      dockerfile: ./docker/queue/Dockerfile
    depends_on:
      - mysql
    env_file: .env
    volumes:
      - .:/var/www
    working_dir: /var/www
