version: '3'

services:
  app:
    image: joaomisturini/laravel-app
    networks:
      - my-net
    volumes:
      - /var/www/storage
    env_file: ".env.prod"

  web:
    image: joaomisturini/laravel-web
    networks:
      - my-net
    ports:
      - 80:80
      - 443:443

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: ecommerce
      MYSQL_USER: ecommerce
      MYSQL_PASSWORD: 123456
    networks:
      - my-net
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:3.2
    networks:
      - my-net

networks:
  my-net:

volumes:
  dbdata:
